name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: permission for gradle wrapper
        run: chmod +x gradlew

      - name: Build Process
        run: ./gradlew :process-service:bootJar

      - name: Build Rest
        run: ./gradlew :rest-service:bootJar

      - name: Build Docker images
        run: |
          docker build -t ghcr.io/shurick2211/redisdemoapp/rest-service:latest rest-service
          docker build -t ghcr.io/shurick2211/redisdemoapp/process-service:latest process-service

      - name: Run Integration Tests
        run: ./gradlew :test-service:test