name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build all modules
        run: ./gradlew clean build -x test

      - name: Build Docker images
        run: |
          docker build -t ghcr.io/${{ github.repository }}/rest-service:latest rest-service
          docker build -t ghcr.io/${{ github.repository }}/process-service:latest process-service

      - name: Run Integration Tests
        run: ./gradlew :test-service:test